export enum ActionType {
  GDAX_CLIENT_SNAPSHOT = "GDAX_CLIENT_SNAPSHOT",
  GDAX_CLIENT_UPDATE_BID = "GDAX_CLIENT_UPDATE_BID",
  GDAX_CLIENT_UPDATE_ASK = "GDAX_CLIENT_UPDATE_ASK",
  GDAX_CLIENT_UPDATE_STATS = "GDAX_CLIENT_UPDATE_STATS"
}
